@extends('layouts.app')
@section('title', 'Produk')
@section('content')
<div class="flex flex-col md:flex-row md:justify-between md:items-center gap-4 mb-6">
    <div><h1 class="text-2xl font-bold">Data Produk</h1><p class="text-gray-500">Kelola produk, harga, dan stok barang.</p></div>
    <a href="{{ route('products.create') }}" class="bg-blue-600 text-white px-4 py-2 rounded-xl text-center">Tambah Produk</a>
</div>
<form method="GET" class="bg-white p-4 rounded-2xl shadow-sm mb-4 flex gap-2"><input name="search" value="{{ request('search') }}" placeholder="Cari nama/kode produk" class="border rounded-xl p-2 flex-1"><button class="bg-slate-900 text-white px-4 py-2 rounded-xl">Cari</button></form>
<div class="bg-white rounded-2xl shadow-sm overflow-x-auto"><table class="w-full text-sm"><thead class="bg-gray-100"><tr><th class="p-3 text-left">Kode</th><th class="p-3 text-left">Produk</th><th class="p-3 text-left">Kategori</th><th class="p-3 text-left">Cabang</th><th class="p-3 text-center">Stok</th><th class="p-3 text-right">Harga Jual</th><th class="p-3 text-center">Status</th><th class="p-3 text-center">Aksi</th></tr></thead><tbody>@forelse($products as $product)<tr class="border-b"><td class="p-3">{{ $product->code }}</td><td class="p-3 font-semibold">{{ $product->name }}</td><td class="p-3">{{ $product->category->name ?? '-' }}</td><td class="p-3">{{ $product->branch->name ?? '-' }}</td><td class="p-3 text-center">{{ $product->stock }} {{ $product->unit }}</td><td class="p-3 text-right">Rp {{ number_format($product->selling_price,0,',','.') }}</td><td class="p-3 text-center">@if($product->stock <= $product->min_stock)<span class="bg-red-100 text-red-700 px-3 py-1 rounded-full">Menipis</span>@else<span class="bg-green-100 text-green-700 px-3 py-1 rounded-full">Aman</span>@endif</td><td class="p-3"><div class="flex gap-2 justify-center"><a href="{{ route('products.edit',$product) }}" class="bg-yellow-400 px-3 py-1 rounded-lg">Edit</a><form action="{{ route('products.destroy',$product) }}" method="POST" onsubmit="return confirm('Hapus produk?')">@csrf @method('DELETE')<button class="bg-red-500 text-white px-3 py-1 rounded-lg">Hapus</button></form></div></td></tr>@empty<tr><td colspan="8" class="p-5 text-center text-gray-500">Produk belum tersedia.</td></tr>@endforelse</tbody></table></div><div class="mt-4">{{ $products->links() }}</div>
@endsection
